/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VUExhibitionForm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author System46
 */
public class VUExhibitionNavigateRecordsForm extends javax.swing.JFrame {
     Connection conn;
     Statement s;
     ResultSet rs;
     String selTable;
      
       
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VUExhibitionNavigateRecordsForm.class.getName());

    /**
     * Creates new form VUExhibitionNavigateRecordsForm
     */
    public VUExhibitionNavigateRecordsForm() {
        initComponents();
    }

    public void CreateStatement() throws ClassNotFoundException, SQLException{
           
    
     Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
     conn = DriverManager.getConnection("jdbc:ucanaccess://D:/VU_Exhibition.accdb");
     System.out.println("Database Connected successfully...!");
     
     //SELECTING DATA FROM OUR VU_Exhibition database table, participants
     selTable = "SELECT * FROM participants";
     
     //Excuting our SQL query
     s=conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
     
     s.executeQuery(selTable);
     rs=s.getResultSet();
     System.out.println("EMAIL ADDRESS: " + rs.getString("StudentName"));
    
    
    
    }
    
    
    //START RETURNING FIRST RECORD FROM participants
    public void First() throws ClassNotFoundException, SQLException{
        CreateStatement();
        
        try{
            rs.first();
            txtStudentNameNav.setText(rs.getString("StudentName"));
            txtRegistrationIDNav.setText(rs.getString("RegistrationID"));
            txtFacultyNav.setText(rs.getString("Faculty"));
            txtProjectTitleNav.setText(rs.getString("ProjectTitleNav"));
            txtContactNumberNav.setText(rs.getString("ContactNumber"));
            txtEmailAddressNav.setText(rs.getString("EmailAddress"));
            
            System.out.println("EMAIL ADDRESS: " + rs.getString("ID"));
            
        }catch(SQLException ex){
        //handling it
        System.out.println("Something went wrong in first Record...!");
        System.out.println("Message: " + ex.getMessage());
        }
        
        
            
    
    
    }
    //END RETURNING
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        intIDNav = new javax.swing.JTextField();
        txtRegistrationIDNav = new javax.swing.JTextField();
        txtStudentNameNav = new javax.swing.JTextField();
        txtFacultyNav = new javax.swing.JTextField();
        txtProjectTitleNav = new javax.swing.JTextField();
        txtContactNumberNav = new javax.swing.JTextField();
        txtEmailAddressNav = new javax.swing.JTextField();
        buttonFirstRecord = new javax.swing.JButton();
        buttonNextRecord = new javax.swing.JButton();
        buttonPreviousRecord = new javax.swing.JButton();
        buttonLastRecord = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VU EXHIBITION PARTICIPANTS - RECORDS NAV");

        jLabel2.setText("ID:");

        jLabel3.setText("Student Name:");

        jLabel4.setText("Registration ID:");

        jLabel5.setText("Faculty : ");

        jLabel6.setText("Project Title:");

        jLabel7.setText("Contact Number :");

        jLabel8.setText("Email Address:");

        intIDNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intIDNavActionPerformed(evt);
            }
        });

        txtStudentNameNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameNavActionPerformed(evt);
            }
        });

        txtContactNumberNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberNavActionPerformed(evt);
            }
        });

        buttonFirstRecord.setText("First ");
        buttonFirstRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFirstRecordActionPerformed(evt);
            }
        });

        buttonNextRecord.setText("Next");
        buttonNextRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextRecordActionPerformed(evt);
            }
        });

        buttonPreviousRecord.setText("Previous");

        buttonLastRecord.setText("Last");

        jButton1.setText("Connection Status!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonFirstRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonNextRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonPreviousRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonLastRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRegistrationIDNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentNameNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFacultyNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtProjectTitleNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtContactNumberNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmailAddressNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(intIDNav, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(intIDNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRegistrationIDNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentNameNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacultyNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProjectTitleNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtContactNumberNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmailAddressNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFirstRecord)
                    .addComponent(buttonNextRecord)
                    .addComponent(buttonPreviousRecord)
                    .addComponent(buttonLastRecord))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void intIDNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intIDNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intIDNavActionPerformed

    private void txtStudentNameNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameNavActionPerformed

    private void txtContactNumberNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberNavActionPerformed

    private void buttonNextRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNextRecordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             // TODO add your handling code here:
             CreateStatement();
         } catch (ClassNotFoundException | SQLException ex) {
             System.getLogger(VUExhibitionNavigateRecordsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonFirstRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFirstRecordActionPerformed
         try {
             // TODO add your handling code here:
             First();
         } catch (ClassNotFoundException | SQLException ex) {
             System.getLogger(VUExhibitionNavigateRecordsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             
         
         }
    }//GEN-LAST:event_buttonFirstRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VUExhibitionNavigateRecordsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFirstRecord;
    private javax.swing.JButton buttonLastRecord;
    private javax.swing.JButton buttonNextRecord;
    private javax.swing.JButton buttonPreviousRecord;
    private javax.swing.JTextField intIDNav;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContactNumberNav;
    private javax.swing.JTextField txtEmailAddressNav;
    private javax.swing.JTextField txtFacultyNav;
    private javax.swing.JTextField txtProjectTitleNav;
    private javax.swing.JTextField txtRegistrationIDNav;
    private javax.swing.JTextField txtStudentNameNav;
    // End of variables declaration//GEN-END:variables
}
